# Usar imagen de NODE
FROM node:18-alpine as builder

WORKDIR /app

# Instala @nestjs/cli globalmente
RUN npm install -g @nestjs/cli

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build

#ETAPA DE RUNTIME

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["node", "dist/main.js"]
